ProjetoS2B/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoS2B.Models;
using System.Web.Security;

namespace ProjetoS2B.Controllers
{
    public class UserLoginController : Controller
    {
        private DataBaseContext db = new DataBaseContext();

        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(Usuario user)
        {
           Usuario user1 = db.Usuarios.FirstOrDefault(u => u.Login == user.Login);
           // if (ModelState.IsValid)
            //{
                if (IsValid(user.Login, user.Senha))
                {
                Session["UserID"] = user1.UserID.ToString();
                Session["Login"] = user.Login.ToString();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Login Falhou");
                }
            //}
            return View(user);
        }

        [HttpGet]
        public ActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registro([Bind(Include = "UserID,NroVendas,NroCompras,NroLikes,NroDislikes,Rating,Senha,SenhaRocks,Nome,Sobrenome,CPF,Login")]Usuario user)
        {
            if (ModelState.IsValid)
            {
                var crypto = new SimpleCrypto.PBKDF2();
                var encriptado = crypto.Compute(user.Senha);
                var dbUser = db.Usuarios.Create();
                //dbUser = user;
                dbUser.NroCompras = 0;
                dbUser.NroDislikes = 0;
                dbUser.NroVendas = 0;
                dbUser.NroLikes = 0;
                dbUser.Nome = user.Nome;
                dbUser.Sobrenome = user.Sobrenome;
                dbUser.Login = user.Login;
                dbUser.CPF = user.CPF;
                dbUser.Senha = encriptado;
                dbUser.SenhaRocks = crypto.Salt;
                db.Usuarios.Add(dbUser);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Registro inválido, confira seus dados");
            }
            return View();
        }

        public ActionResult LogOut()
        {
            Session["UserID"] = null;
            Session["Login"] = null;
            return RedirectToAction("Index", "Home");
        }

        private bool IsValid(string login, string senha)
        {
            bool valida = false;
            var crypto = new SimpleCrypto.PBKDF2();
            var user = db.Usuarios.FirstOrDefault(u => u.Login == login);
            if (user != null)
            {
                if (user.Senha == crypto.Compute(senha, user.SenhaRocks))
                {
                    valida = true;
                }
            }
            return valida;
        }

    }
}

ProjetoS2B/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        <!--Links para criar logar ou deslogar-->
        <div style="width:auto; background-color: rgba(248, 237, 237, 0.34);">
            @if (Session["UserID"] != null)
            {
                <strong>@Html.Encode(Session["Login"])</strong>
                @Html.ActionLink("Log Out", "LogOut", "UserLogin")
            }
            else
            {
                @Html.ActionLink("Cria Usuario", "Registro", "UserLogin")
                <span> | </span>
                @Html.ActionLink("Log In", "LogIn", "UserLogin")
            }
        </div>


        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>