ProjetoS2B/Controllers/AddProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoS2B.Models;

namespace ProjetoS2B.Controllers
{
    public class AddProdutoController : Controller
    {
        // GET: AddProduto
        public ActionResult Index()
        {
            if (Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", "UserLogin");
            }
        }

        [HttpPost]
        public ActionResult Index(Produto produto)
        {
            if(Session["UserID"] != null)
            {
                int id = Convert.ToInt32(Session["UserID"]);
                using(var db = new DataBaseContext())
                {
                    Usuario user = db.Usuarios.FirstOrDefault(u => u.UserID == id);
                    if(user != null)
                    {
                        user.NovaVenda(produto.Description, produto.Valor, produto.GeneroProduto, id);
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            else
            {
                return RedirectToAction("LogIn", "UserLogin");
            }
            return View(produto);
        }
    }
}

ProjetoS2B/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjetoS2B.Models;

namespace ProjetoS2B.Controllers
{
    public class HomeController : Controller
    {
        DataBaseContext db = new DataBaseContext();

        public ActionResult Index()
        {
            List<Produto> lista = new List<Produto>();
            List<Produto> disponiveis = new List<Produto>();
            lista = db.Produtos.ToList();
            foreach (Produto d in lista)
            {
                if (d.Disponivel == true)
                {
                    disponiveis.Add(d);
                }
            }
            return View(disponiveis);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProjetoS2B/Views/Home/Index.cshtml
@model IEnumerable<ProjetoS2B.Models.Produto>
@{
    ViewBag.Title = "Home Page";
}
@Html.ActionLink("Adiciona Novo Produto", "Index", "AddProduto")
<h2>Index</h2>


<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.GeneroProduto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.GeneroProduto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ProdutoID }) |
                @Html.ActionLink("Comprar", "", new { id = item.ProdutoID })
            </td>
        </tr>
    }

</table>